@HostAddress = http://localhost:5125

POST {{HostAddress}}/api/user/create
Accept: application/json
Content-Type: application/json

{
  "id": 0,
  "firstName": "John",
  "lastName": "Doe",
  "age": 30
}

###

POST {{HostAddress}}/api/user/create
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "firstName": "John",
  "lastName": "Doe",
  "age": 30
}

###

POST {{HostAddress}}/api/user/create
Accept: application/json
Content-Type: application/json

{
  "id": 2,
  "firstName": "John",
  "lastName": "Doe",
  "age": 30
}

###
