version: "3"
services:
  {service-name}:
    image: {image-name}
    container_name: {container-name}
    volumes:
      - ./data:/www/wwwroot/data
      - ./storage:/www/storage
    ports:
      - "{80:80}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS={http://+:80}
    networks:
      - {network}
networks:
  {network}: